import * as fs from 'fs'
import * as path from 'path'
import * as yaml from 'js-yaml'
import type { HAClient, HAState } from './ha-client.js'

const DOMAIN_LABELS: Record<string, string> = {
  light: 'Lights',
  switch: 'Switches',
  climate: 'Climate',
  cover: 'Covers',
  media_player: 'Media Players',
  lock: 'Locks',
  sensor: 'Sensors',
  binary_sensor: 'Binary Sensors',
  fan: 'Fans',
  vacuum: 'Vacuums',
  scene: 'Scenes',
  script: 'Scripts',
  automation: 'Automations',
  input_boolean: 'Input Booleans',
  alarm_control_panel: 'Alarm',
  camera: 'Cameras',
  humidifier: 'Humidifiers',
  water_heater: 'Water Heaters',
}

// Domains that are system/metadata — unlikely to be directly controlled
const SKIPPED_DOMAINS = new Set([
  'device_tracker',
  'person',
  'sun',
  'weather',
  'zone',
  'update',
  'number',
  'select',
  'input_number',
  'input_select',
  'input_text',
  'persistent_notification',
  'system_log',
  'recorder',
  'logbook',
  'conversation',
  'stt',
  'tts',
])

export async function runSetup(haClient: HAClient, haDir: string): Promise<void> {
  console.log('Fetching entities from Home Assistant...')

  let states: HAState[]
  try {
    states = await haClient.getStates()
  } catch (err) {
    console.error('Failed to connect to Home Assistant:', err)
    console.error('Check your haUrl and haToken configuration.')
    process.exit(1)
  }

  // Group by domain
  const byDomain = new Map<string, HAState[]>()
  for (const state of states) {
    const domain = state.entity_id.split('.')[0]
    if (SKIPPED_DOMAINS.has(domain)) continue
    if (!byDomain.has(domain)) byDomain.set(domain, [])
    byDomain.get(domain)!.push(state)
  }

  if (!fs.existsSync(haDir)) {
    fs.mkdirSync(haDir, { recursive: true })
    console.log(`Created directory: ${haDir}`)
  }

  let filesCreated = 0
  let filesSkipped = 0

  for (const [domain, entities] of [...byDomain.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const filename = `${domain}.yaml`
    const filePath = path.join(haDir, filename)

    if (fs.existsSync(filePath)) {
      console.log(`  Skipping ${filename} (already exists — delete to regenerate)`)
      filesSkipped++
      continue
    }

    const label = DOMAIN_LABELS[domain] ?? domain

    const devices = entities
      .sort((a, b) => a.entity_id.localeCompare(b.entity_id))
      .map((e) => ({
        entity_id: e.entity_id,
        name: e.attributes.friendly_name ?? e.entity_id,
        enabled: true,
      }))

    const fileData = {
      room: null as null,
      devices,
    }

    const header =
      `# ${label} — auto-generated by openclaw ha:init\n` +
      `# Set 'room' at the top to assign all devices to a room, or override per device.\n` +
      `# Set 'enabled: false' on a device to hide it from the agent.\n\n`

    const yamlContent = yaml.dump(fileData, { lineWidth: 120, quotingType: '"' })

    fs.writeFileSync(filePath, header + yamlContent, 'utf-8')
    console.log(`  Created ${filename} (${devices.length} device${devices.length !== 1 ? 's' : ''})`)
    filesCreated++
  }

  console.log('')
  if (filesCreated > 0) {
    console.log(`Done. Created ${filesCreated} file(s) in ${haDir}`)
    console.log('Edit the files to:')
    console.log("  • Set 'room:' at the file level or per device")
    console.log("  • Set 'enabled: false' on devices you don't want the agent to use")
    console.log('  • Give devices clearer friendly names if needed')
  } else {
    console.log(`No new files created. ${filesSkipped} file(s) already existed.`)
  }
}
