import * as fs from 'fs'
import * as path from 'path'
import * as yaml from 'js-yaml'
import type { HAClient, HAState } from './ha-client.js'

// Domains that are system/metadata — unlikely to be directly controlled
const SKIPPED_DOMAINS = new Set([
  'device_tracker',
  'person',
  'sun',
  'weather',
  'zone',
  'update',
  'number',
  'select',
  'input_number',
  'input_select',
  'input_text',
  'persistent_notification',
  'system_log',
  'recorder',
  'logbook',
  'conversation',
  'stt',
  'tts',
])

interface DeviceRecord {
  entity_id: string
  name: string
  room: string | null
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export async function runSetup(haClient: HAClient, haDir: string): Promise<void> {
  console.log('Fetching entities from Home Assistant...')

  let states: HAState[]
  try {
    states = await haClient.getStates()
  } catch (err) {
    console.error('Failed to connect to Home Assistant:', err)
    console.error('Check your haUrl and haToken configuration.')
    process.exit(1)
  }

  // Fetch area and entity registry to get room assignments
  const [areas, entityRegistry] = await Promise.all([
    haClient.getAreas(),
    haClient.getEntityRegistry(),
  ])

  const areaById = new Map(areas.map((a) => [a.area_id, a.name]))
  const roomByEntityId = new Map(
    entityRegistry
      .filter((e) => e.area_id)
      .map((e) => [e.entity_id, areaById.get(e.area_id!) ?? null]),
  )
  // Also pick up user-defined names from the entity registry
  const registryNameByEntityId = new Map(
    entityRegistry
      .filter((e) => e.name || e.original_name)
      .map((e) => [e.entity_id, e.name ?? e.original_name]),
  )

  const hasRoomData = roomByEntityId.size > 0
  console.log(
    hasRoomData
      ? `Found ${areas.length} area(s) — grouping by room.`
      : 'No area data found — grouping by entity type.',
  )

  // Build device list, skipping system domains
  const devices: DeviceRecord[] = states
    .filter((s) => !SKIPPED_DOMAINS.has(s.entity_id.split('.')[0]))
    .map((s) => ({
      entity_id: s.entity_id,
      name:
        registryNameByEntityId.get(s.entity_id) ??
        (s.attributes.friendly_name as string | undefined) ??
        s.entity_id,
      room: roomByEntityId.get(s.entity_id) ?? null,
    }))
    .sort((a, b) => a.entity_id.localeCompare(b.entity_id))

  if (!fs.existsSync(haDir)) {
    fs.mkdirSync(haDir, { recursive: true })
    console.log(`Created directory: ${haDir}`)
  }

  let filesCreated = 0
  let filesSkipped = 0

  if (hasRoomData) {
    // Group by room — one file per room, unassigned devices go to unassigned.yaml
    const byRoom = new Map<string, DeviceRecord[]>()
    for (const device of devices) {
      const key = device.room ?? 'unassigned'
      if (!byRoom.has(key)) byRoom.set(key, [])
      byRoom.get(key)!.push(device)
    }

    for (const [room, roomDevices] of [...byRoom.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const filename = `${slugify(room)}.yaml`
      const filePath = path.join(haDir, filename)

      if (fs.existsSync(filePath)) {
        console.log(`  Skipping ${filename} (already exists — delete to regenerate)`)
        filesSkipped++
        continue
      }

      const fileData = {
        room: room === 'unassigned' ? null : room,
        devices: roomDevices.map(({ entity_id, name }) => ({ entity_id, name, enabled: true })),
      }

      const header =
        `# ${room === 'unassigned' ? 'Unassigned devices' : room} — auto-generated by openclaw ha:init\n` +
        `# Set 'enabled: false' on a device to hide it from the agent.\n\n`

      fs.writeFileSync(filePath, header + yaml.dump(fileData, { lineWidth: 120, quotingType: '"' }), 'utf-8')
      console.log(`  Created ${filename} (${roomDevices.length} device${roomDevices.length !== 1 ? 's' : ''})`)
      filesCreated++
    }
  } else {
    // Fall back to grouping by domain
    const DOMAIN_LABELS: Record<string, string> = {
      light: 'Lights', switch: 'Switches', climate: 'Climate', cover: 'Covers',
      media_player: 'Media Players', lock: 'Locks', sensor: 'Sensors',
      binary_sensor: 'Binary Sensors', fan: 'Fans', vacuum: 'Vacuums',
      scene: 'Scenes', script: 'Scripts', automation: 'Automations',
      input_boolean: 'Input Booleans', alarm_control_panel: 'Alarm',
      camera: 'Cameras', humidifier: 'Humidifiers', water_heater: 'Water Heaters',
    }

    const byDomain = new Map<string, DeviceRecord[]>()
    for (const device of devices) {
      const domain = device.entity_id.split('.')[0]
      if (!byDomain.has(domain)) byDomain.set(domain, [])
      byDomain.get(domain)!.push(device)
    }

    for (const [domain, domainDevices] of [...byDomain.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const filename = `${domain}.yaml`
      const filePath = path.join(haDir, filename)

      if (fs.existsSync(filePath)) {
        console.log(`  Skipping ${filename} (already exists — delete to regenerate)`)
        filesSkipped++
        continue
      }

      const label = DOMAIN_LABELS[domain] ?? domain
      const fileData = {
        room: null as null,
        devices: domainDevices.map(({ entity_id, name }) => ({ entity_id, name, enabled: true })),
      }

      const header =
        `# ${label} — auto-generated by openclaw ha:init\n` +
        `# Set 'room' at the top to assign all devices in this file to a room.\n` +
        `# Set 'enabled: false' on a device to hide it from the agent.\n\n`

      fs.writeFileSync(filePath, header + yaml.dump(fileData, { lineWidth: 120, quotingType: '"' }), 'utf-8')
      console.log(`  Created ${filename} (${domainDevices.length} device${domainDevices.length !== 1 ? 's' : ''})`)
      filesCreated++
    }
  }

  console.log('')
  if (filesCreated > 0) {
    console.log(`Done. Created ${filesCreated} file(s) in ${haDir}`)
    if (!hasRoomData) {
      console.log("Tip: assign rooms in Home Assistant (Settings → Areas) and re-run 'openclaw ha:init' to regenerate room-based files.")
    }
  } else {
    console.log(`No new files created. ${filesSkipped} file(s) already existed.`)
  }
}
